name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest

    env:
      COREHOST_TRACE: false
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # prevent the caching of the packages on the build machine
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      # prevent the download of the XML documentation for the packages
      NUGET_XMLDOC_MODE: skip

    steps:
      - uses: actions/checkout@v2

      - name: Setup Nuget cache
        uses: actions/cache@v2
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/Minifier/Minifier.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.1

      - name: Setup Nuget
        uses: nuget/setup-nuget@v1.0.2

      - name: Restore Nuget packages
        shell: powershell
        run: nuget restore

      - name: Build Project for .Net 4.6
        shell: powershell
        run: MSBuild -p:Configuration=Release -detailedSummary -noLogo

      - name: Compress Build Artifacts
        shell: powershell
        run: Compress-Archive ./Minifier/bin/Release/*/* ./Minifier/bin/Release/minifier_release.zip

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: URL Minifier in Azure
          body: 'All notable changes to this version has been documented in the CHANGELOG.md file.'
          # This will update existing tags if any
          allowUpdates: true
          artifacts: ${{ github.workspace }}/Minifier/bin/Release/minifier_release.zip
          artifactContentType: application/octet-stream

      - name: Deploy app to Azure
        run: echo "::warning file=Under development..."
